version: "3"
services:
  mongodb:
    container_name: anxietydb
    image: mongo:latest
    volumes:
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
      - ./scripts/mongo/seed/:/home/mongodb/seed
      - anxietydb:/data/db
    command: ['--auth']
    restart: always
    env_file:
      - .env
    ports:
      - "28017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ADMIN_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_COLLECTION_NAME=$DB_USERS
      - MONGO_HOSTNAME=mongodb
    networks:
      - mongo-network
volumes:
  anxietydb:
    driver: local

networks:
  mongo-network:
    driver: bridge